const productsChicharron = [
    {
      id: 1,
      name: 'Chicharrón Crujiente',
      description: 'Chicharrón de cerdo crujiente, preparado al estilo tradicional peruano.',
      price: '15.00',
      image: 'https://placehold.co/300x200?text=Producto+1',
      whatsapp: '989974555',
    },
    {
      id: 2,
      name: 'Chicharrón con Camote',
      description: 'Delicioso chicharrón acompañado con camote frito, una combinación perfecta.',
      price: '18.00',
      image: 'https://placehold.co/300x200?text=Producto+2',
      whatsapp: '989974555',
    },
    {
      id: 3,
      name: 'Chicharrón de Pavo',
      description: 'Elaborado con pavo, crujiente y jugoso, ideal para compartir en familia.',
      price: '20.00',
      image: 'https://placehold.co/300x200?text=Producto+3',
      whatsapp: '989974555',
    },
    {
      id: 4,
      name: 'Tamalito de Cerdo',
      description: 'Tamalito relleno de cerdo, con un sabor tradicional y especias de la región.',
      price: '12.00',
      image: 'https://placehold.co/300x200?text=Producto+4',
      whatsapp: '989974555',
    },
    {
      id: 5,
      name: 'Chicharrón con Ensalada',
      description: 'Chicharrón servido con una ensalada fresca de la huerta.',
      price: '16.00',
      image: 'https://placehold.co/300x200?text=Producto+5',
      whatsapp: '989974555',
    },
    {
      id: 6,
      name: 'Sopa de Chicharrón',
      description: 'Una sopa caliente con chicharrón, ideal para el frío.',
      price: '14.00',
      image: 'https://placehold.co/300x200?text=Producto+6',
      whatsapp: '989974555',
    },
    {
      id: 7,
      name: 'Chicharrón con Papas Fritas',
      description: 'Chicharrón acompañado con papas fritas caseras.',
      price: '17.00',
      image: 'https://placehold.co/300x200?text=Producto+7',
      whatsapp: '989974555',
    },
    {
      id: 8,
      name: 'Arepa de Chicharrón',
      description: 'Deliciosa arepa rellena con chicharrón y un toque de salsa picante.',
      price: '13.00',
      image: 'https://placehold.co/300x200?text=Producto+8',
      whatsapp: '989974555',
    },
];

export default productsChicharron;